columns:
  required:
    - sample_id
    - time_s
    - temp_C
    - rho_rel
    - pressure_mpa
technique_profile:
  name: UHS
  heating_rate_c_per_min: 50
  atmosphere: Inerte
  notes: Ultra-high speed sintering com pressão uniaxial moderada.
msc:
  ea_kj:
    - 150
    - 225
    - 325
  metric: densified
features:
  include:
    - global
    - stage
    - electric
ml:
  targets:
    - mechanism_label
segmentation:
  bounds:
    - 50
    - 65
    - 85
electric_features:
  enabled: true
