name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Run tests
        run: pytest -q

      - name: Build wheel
        run: |
          python -m pip install build
          python -m build --wheel --outdir dist

      - name: Publish GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Ogum ML Lite ${{ github.ref_name }}
          draft: false
          prerelease: false
          allowUpdates: true
          artifacts: "dist/*.whl,artifacts/**/*"
          artifactErrorsFailBuild: false
